#!/usr/bin/env bash
# This script tells the story of each user in /etc/passwd
while IFS=':' read -r username info home shell gid password uid;do
    echo "the user $username is part of the $gid gang, lives in $home and rides $shell. $uid's plase is protected by the passcode $password, more info about the user here: $info"
done
